### ISSUE TITLE
The fee from a basic change tx is higher than expected

### ISSUE THREAD

**Issue by mrz1836** [libsv/go-bt#2]
See this test:
https://github.com/mrz1836/go-bt/blob/5a57029d39d4d9a89ba65e2f7c098c70419467a8/tx_test.go#L223

I would expect the fee to be closer to 0.5

**Comment by jadwahab** [comment]
just checking it, the issue is not that the fee is wrong, it's that the test is using `signAuto` which signs the tx if it can and apparently it's not signing the tx (empty scriptsig) for some reason. maybe the private key used is not the right one for the utxo
<img width="586" alt="image" src="https://user-images.githubusercontent.com/15110087/99316428-45ea0900-285c-11eb-8e17-e50045aa5048.png">

**Comment by jadwahab** [comment]
so basically if the tx were properly signed it should be the correct fees paid

**Comment by jadwahab** [comment]
fixed the test here 9dad45520269edd4184cba1cfe3b08e4d80c3aa6
